### ISSUE TITLE
BOM

### ISSUE THREAD

**Issue by petiepooo** [dwillmore/TSSOP20_breakout#2]
Do you have a list of recommended part numbers, or a link to a shared Mouser project with the BOM?  Please?  This is a fantastic idea, and I'm planning to make a few.

**Comment by dwillmore** [comment]
I was just thinking last night that I never did clarify that part.  I can post a generic BOM, but the board is meant to be flexable and accomodate most regulators in the common SO-23-5 footprint.  There's a pad for those which require a compensation capacitor (which can be left off for regulators that don't need it or say to leave the pin open).

You can use any 0603 parts you have handy.  You'll need to use decoupling caps which fit your specific regulator.  This is normally from 1 to 10uF, but it does vary with your part.  The voltage rating of the input may also need to vary depending on how you plan to power the board--from USB a 6.3V cap should be fine, but you may wish to power it some other way and the voltage rating would need to be adjusted appropriately.

The USB series resistors will vary with the part in question as well.  Low and full speed devices may not need them--and can just short the pads across--which high speed parts will likely need them, but they value may vary with the particular part used though they are typically 22 Ohms (again the footprint is 0603).  

Then there is the 'spare' 0603 footprint.  I included this for chips which are bitbanging USB and don't have a built in USB PHY so they need some external ability to pull up one of the USB signals lines to 3.3V with a 1.5K resistor.  This footprint has patch pads on both ends and can be used to add any 0603 part to the board.  If the part needs an analog supply, this could be for a decoupling cap.

I'll try to post a BOM for the two different regulators which I have, but there is not specific BOM for this design as it's mean to adapt to the specific chip on the board and to parts that the builder may have on hand since the purpose of the board is to make them ahead of time and have them on hand when some random TSSOP20 chip falls into their lap and they need it mounted up ASAP.  You dig through bins or steal parts off of other boards (sorry unsed bluepill but all your parts are belong to me!  Oh, no someone set us up the BOM!)

**Comment by petiepooo** [comment]
So it's more nuanced than just "order and mount these parts."  I get that now.  I think it would be useful to at least have the USB port's PN, still, and some examples of regulators you used in your examples.  

Thanks.  I appreciate your quick response and clarification.

**Comment by dwillmore** [comment]
I can and will provide a few 'typical' BOMs and some suggestions.  Thanks for bringing up this issue, I'm not sure I would have made the BOM section as useful without your prompting.

**Comment by dwillmore** [comment]
@petiepooo Can you take a look at the main Readme.md to see if that satisfies yoru needs?  If so, please close the issue.  Thank you.
